# URLS FROM FLYSCANNER

URLS:
  - https://globalbiletix.onlineota.com/a/flight/search/result/all?departure_id=6IST1TR&departure=Istanbul,%20Istanbul%20Havalimani%20(IST),%20TR&destination_id=6ADA1TR&destination=Adana,%20Adana%20Sakirpasa%20Havalimani%20(ADA),%20TR&departure_date=24.08.2023&adult_num=1&child_num=0&infant_num=0
  - https://globalbiletix.onlineota.com/a/flight/search/result/all?departure_id=6IST1TR&departure=Istanbul,%20Istanbul%20Havalimani%20(IST),%20TR&destination_id=6SHA2TR&destination=Shanghai,%20Tum%20Havaalanlari%20(SHA),%20CN&departure_date=30.08.2023&return_date=21.09.2023&adult_num=1&child_num=0&infant_num=0


# SENDER EMAIL, SMTP TOKEN & RECEIVER EMAIL HERE <<<
SMTP:
  USE: True # Change to False if you will not use email sender system.
  sender_email: scraperflight@gmail.com           # <<< SENDER EMAIL
  smtp_key:                     # <<< SMTP TOKEN 
  receiver_email: erkamesen789@gmail.com       # <<< RECEIVER EMAIL



## (Optional) TELEGRAM - Set your APIKEY and add ChatIDs
TELEGRAM:
  USE: False # Change to False if you will not use telegram.
  TELEGRAM_APIKey: 
  TELEGRAM_chatID:  # 1